/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CLAB_10
 */
public class MethodsOfString extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MethodsOfString() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name 1");

        jLabel2.setText("Name 2");

        jLabel3.setText("Name3");

        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ta.setColumns(30);
        ta.setRows(30);
        ta.setMinimumSize(new java.awt.Dimension(4, 50));
        jScrollPane1.setViewportView(ta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(tf2)
                            .addComponent(tf1))
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String name1= new String();
      name1=tf1.getText();
      String name2=new String();
      name2=tf2.getText();
      String name3= new String();
      name3=tf3.getText();
      lengthOFString(name1);
      characteratIndex(name1);
      compareStrings(name1,name2);
      concatination1(name1,name2);
      concatination2(name2,name3);
      occurencesOFN(name3);
      subString(name1);
      replaceCharacter(name3);
      caseConversion(name1);
              
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */public void lengthOFString(String name)
     {
         ta.append("length of string "+name + " is  "+name.length());
     }
       public void characteratIndex(String name)
       {
           ta.append("\n at 0 the character is "+name.charAt(0));
           ta.append("\n at 3 the charcater is "+name.charAt(3));
       }
       public void compareStrings(String name1,String name2)
       {
           ta.append("\ncompare "+name1+" and "+name2+" = "+name1.compareTo(name2));
           ta.append("\ncompare"+name2+"and"+name1+"="+name2.compareTo(name1));
           ta.append("\ncompare"+name2+"and"+name2+"="+name2.compareTo(name2));
            if(name1.compareTo(name2)==0)
                ta.append("\n the same");
            else
                ta.append("\n not the same");
            ta.append("\nequals"+name2+"and"+name1+"="+name2.equals(name1));
            ta.append("\nequals"+name2+"and"+name2+"="+name2.equals(name2));
        }
         public void concatination1(String name1,String name2)
         {
             name1=name1.concat(" ");
             name1=name1.concat(name2);
             ta.append("\n name1="+name1);
         }
        public void concatination2(String name1,String name2)
        {
            name1=name1+" "+name2 ;
            ta.append("\n name1= "+name1);
                       
        }
          public void occurencesOFN(String name)
          {
           ta.append("\n first occurence of 'n' in "+ name+"is at index"+name.indexOf('n'));
           ta.append("\n last occurence of 'n' in "+ name+"is at index"+name.lastIndexOf('n'));
           ta.append("\n first occurence of 'Z' in "+ name+"is at index"+name.indexOf('Z'));
          }
          public void subString(String name1)
          {
              ta.append("\n Substring from index 4 onwards=" +name1.substring(4,8));
              String name2= name1.substring(0,name1.length());
              ta.append("\n entire copy of "+ name1+ "="+ name2);
              name2=name1.substring(0,2);
              ta.append("\n substring of index 0 to 2="+ name2); 
              name2=name2.concat(name1.substring(name1.indexOf(' '),name1.indexOf(' ')+3));
              ta.append("\n name2="+ name2);
          }
           public void  replaceCharacter(String name)
           {
             name=name.replace('R','.');
             name=name.replace('o','p');
             ta.append("\n name="+name);
           }
          public void caseConversion(String name1)
          {
              name1 = name1.toLowerCase();
              ta.append("\n name1="+name1);
              name1=name1.toUpperCase();
              ta.append("\n name1=" +name1);
              String name2=name1.substring(0,1);
              String name3=name1.substring(1,5);
              name2=name2.concat(name3.toLowerCase());
              ta.append("\n name2="+name2);
              
          }
           
           
       
               
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MethodsOfString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MethodsOfString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MethodsOfString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MethodsOfString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MethodsOfString().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
